version = 0.1
[default.deploy.parameters]
stack_name = "new-upload-to-s3"
resolve_s3 = true
s3_prefix = "new-upload-to-s3"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "BucketName=\"ats-cloudinityinc\""
