AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template to upload files to S3 with full S3 and CloudWatch access
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
Resources:
  UploadToS3Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: UploadToS3Function
      Handler: upload_to_s3.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
        - UploadToS3FunctionRole
        - Arn
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /upload/{filename}
            Method: post
            RestApiId:
              Ref: ApiWithCors
      Environment:
        Variables:
          BUCKET_NAME: ats-cloudinityinc
    Metadata:
      SamResourceId: UploadToS3Function
  ApiWithCors:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''OPTIONS,POST'''
        AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
        AllowOrigin: '''*'''
  UploadToS3FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: LambdaFullS3AndCloudWatchAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:*
            Resource: arn:aws:s3:::ats-cloudinityinc/*
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
  MyLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
        - UploadToS3Function
        - Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiWithCors}/*/*/*
